FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/worker ./cmd/worker

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=build /out/worker /app/worker
COPY --from=build /src/migrations /app/migrations
EXPOSE 9090
ENTRYPOINT ["/app/worker"]
